    @Author: Nishanth
    @Date: 06-04-2022 11:20:00
    @Last Modified by: Nishanth
    @Last Modified Date: 06-04-2022 11:20:00
    @Title: A list practice numpy programs

**Import Necessary Libraries**

In [9]:
import numpy as np

1. **Write a Python program to convert a list of numeric value into a one-dimensional NumPy array**

    Expected Output: Original List: [12.23, 13.32, 100, 36.32]\
    One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [10]:
#Create a list and use it to create numpy array
original_list = [12.23, 13.32, 100, 36.32]
array_from_list = np.array(original_list)

#Print the list and numpy array created
print(f"Original List: {original_list}")
print(f"NumPy array: {array_from_list}")
print(f"NumPy array type: {array_from_list.dtype}")

Original List: [12.23, 13.32, 100, 36.32]
NumPy array: [ 12.23  13.32 100.    36.32]
NumPy array type: float64


2. **Create a 3x3 matrix with values ranging from 2 to 10**

    Expected Output:\
    [[ 2 3 4]\
    [ 5 6 7]\
    [ 8 9 10]]

In [11]:
#Create numpy array using arange and reshape it to 3x3 matrix
new_array = np.arange(2,11).reshape((3,3))

print(f"The 3x3 matrix:\n{new_array}")

The 3x3 matrix:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. **Write a Python program to create a null vector of size 10 and update sixth value to 11**

    [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\
    Update sixth value to 11\
    [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [12]:
#Create a null array of size 10
vector_10 = np.zeros(10)
print(f"Null vector: {vector_10}")

vector_10[6] = 11
print(f"Updated vector: {vector_10}")

Null vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated vector: [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. **Write a Python program to reverse an array (first element becomes last)**

    Original array:\
    [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]\
    Reverse array:\
    [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [15]:
#Create an array ranging from 12 to 37
original_arr = np.arange(12,38)
print(f"Original array:\n{original_arr}")

#Reverse the array
reversed_arr = original_arr[::-1]
print(f"Reversed array:\n{reversed_arr}")

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]
