```
    @Author: Nishanth
    @Date: 06-04-2022 11:20:00
    @Last Modified by: Nishanth
    @Last Modified Date: 06-04-2022 14:13:00
    @Title: A list practice numpy programs
```

**Import Necessary Libraries**

In [2]:
import numpy as np

1. **Write a Python program to convert a list of numeric value into a one-dimensional NumPy array**

    Expected Output: Original List: [12.23, 13.32, 100, 36.32]\
    One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [3]:
#Create a list and use it to create numpy array
original_list = [12.23, 13.32, 100, 36.32]
array_from_list = np.array(original_list)

#Print the list and numpy array created
print(f"Original List: {original_list}")
print(f"NumPy array: {array_from_list}")
print(f"NumPy array type: {array_from_list.dtype}")

Original List: [12.23, 13.32, 100, 36.32]
NumPy array: [ 12.23  13.32 100.    36.32]
NumPy array type: float64


2. **Create a 3x3 matrix with values ranging from 2 to 10**

    Expected Output:\
    [[ 2 3 4]\
    [ 5 6 7]\
    [ 8 9 10]]

In [4]:
#Create numpy array using arange and reshape it to 3x3 matrix
new_array = np.arange(2,11).reshape((3,3))

print(f"The 3x3 matrix:\n{new_array}")

The 3x3 matrix:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. **Write a Python program to create a null vector of size 10 and update sixth value to 11**

    [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\
    Update sixth value to 11\
    [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [5]:
#Create a null array of size 10
vector_10 = np.zeros(10)
print(f"Null vector: {vector_10}")

vector_10[6] = 11
print(f"Updated vector: {vector_10}")

Null vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated vector: [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. **Write a Python program to reverse an array (first element becomes last)**

    Original array:\
    [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]\
    Reverse array:\
    [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [6]:
#Create an array ranging from 12 to 37
original_arr = np.arange(12,38)
print(f"Original array:\n{original_arr}")

#Reverse the array
reversed_arr = original_arr[::-1]
print(f"Reversed array:\n{reversed_arr}")

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. **Write a Python program to create a 2d array with 1 on the border and 0 inside**

    Expected Output:\
    Original array:\
    [[ 1. 1. 1. 1. 1.]\
    [ 1. 1. 1. 1. 1.]\
    [ 1. 1. 1. 1. 1.]\
    [ 1. 1. 1. 1. 1.]\
    [ 1. 1. 1. 1. 1.]]

    1 on the border and 0 inside in the array\
    [[ 1. 1. 1. 1. 1.]\
    [ 1. 0. 0. 0. 1.]\
    [ 1. 0. 0. 0. 1.]\
    [ 1. 0. 0. 0. 1.]\
    [ 1. 1. 1. 1. 1.]]

In [7]:
#Method to create bordered arrays 1 as border
def bordered_arrays_one(rows: int, cols: int):
    """
        Description:
            Creates a 2d array of dimension rows x cols.
            Sets the border values to 1, and insides as 0
        
        Parameter:
            rows: row dimension
            cols: column dimension
        
        Return:
            None
    """
    if rows < 3 or cols < 3:
        print("Rows and columns must be greater than 2")
        return None
    #create an array filled with 1 of dimension 5X5
    border_arr = np.ones((rows,cols))
    print(f"Original array:\n{border_arr}")

    #Set values inside border as 0
    border_arr[1:-1,1:-1] = 0
    print(f"Bordered array:\n{border_arr}")

In [8]:
#create bordered arrays using the bordered_arrays_one function
bordered_arrays_one(5,4)

Original array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Bordered array:
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


6. **Write a Python program to add a border (filled with 0's) around an existing array**
    Expected Output:\
    Original array:\
    [[ 1. 1. 1.]\
    [ 1. 1. 1.]\
    [ 1. 1. 1.]]\
    1 on the border and 0 inside in the array\
    [[ 0. 0. 0. 0. 0.]\
    [ 0. 1. 1. 1. 0.]\
    [ 0. 1. 1. 1. 0.]\
    [ 0. 1. 1. 1. 0.]\
    [ 0. 0. 0. 0. 0.]]

In [9]:
#Method to create bordered arrays, 0 as border
def bordered_arrays_zero(zero_arr: np.ndarray):
    """
        Description:
            Creates a 2d array of dimension rows x cols.
            Sets the border values to 0, and insides as 1
        
        Parameter:
            zero_arr: 2D array
        
        Return:
            None
    """
    if zero_arr.ndim != 2:
        print("Must be a 2D array")
        return None
    rows, cols = zero_arr.shape
    if rows < 3 or cols < 3:
        print("Rows and columns must be greater than 2")
        return None
    #create an array filled with 0's
    border_arr = np.zeros((rows+1,cols+1))

    #Set values inside border as 1
    border_arr[1:-1,1:-1] = 1
    print(f"Original array:\n{zero_arr}")
    print(f"Bordered array:\n{border_arr}")

In [10]:
#create bordered arrays using the bordered_arrays_zero function
sample_zero_arr = np.ones((5,6))
bordered_arrays_zero(sample_zero_arr)

Original array:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Bordered array:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


7. **Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern**

    Checkerboard pattern:\
    [[0 1 0 1 0 1 0 1]\
    [1 0 1 0 1 0 1 0]\
    [0 1 0 1 0 1 0 1]\
    [1 0 1 0 1 0 1 0]\
    [0 1 0 1 0 1 0 1]\
    [1 0 1 0 1 0 1 0]\
    [0 1 0 1 0 1 0 1]\
    [1 0 1 0 1 0 1 0]]

In [11]:
#create size 8x8 array filled with 1's
checkerboard = np.ones((8,8))

#Set alternate values to 0
checkerboard[::2, ::2] = 0
checkerboard[1::2, 1::2] = 0

print(f"Checkerboard pattern:\n{checkerboard}")

Checkerboard pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. **Write a Python program to convert a list and tuple into arrays**

    List to array:\
    [1 2 3 4 5 6 7 8]\
    Tuple to array:\
    [[8 4 6]\
    [1 2 3]]

In [12]:
# Function to convert list or tuple to array
def list_tuple_to_array(iterable_data: list|tuple):
    """
        Description:
            Converts a given list|tuple to array
        
        Parameter:
            iterable_data: it can be a list or tuple
        
        Return:
            None
    """
    array_from_iterable = np.asarray(iterable_data)
    print(f"The iterable given: {iterable_data}")
    print(f"The array created:\n{array_from_iterable}")

In [13]:
# Using the list_tuple_to_array function convert list and tuple to array
sample_list = [1, 2, 3, 4, 5, 6, 7, 8]
sample_tuple = ((8,4,6),(1,2,3))

list_tuple_to_array(sample_list)
list_tuple_to_array(sample_tuple)

The iterable given: [1, 2, 3, 4, 5, 6, 7, 8]
The array created:
[1 2 3 4 5 6 7 8]
The iterable given: ((8, 4, 6), (1, 2, 3))
The array created:
[[8 4 6]
 [1 2 3]]


9. **Write a Python program to append values to the end of an array**

    Expected Output:\
    Original array:\
    [10 20 30]\
    After append values to the end of the array:\
    [10 20 30 40 50 60 70 80 90]

In [14]:
# A function to append list of values to end of array
def append_to_array(arr: np.ndarray, list_of_values: list):
    """
        Description:
            appends the list of values to the array
        
        Parameter:
            arr: a numpy array
            list_of_values: a list of values to append to array
        
        Return:
            None
    """
    arr_updated = np.append(arr, list_of_values)
    print(f"Orignal array:\n{arr}")
    print(f"List of values to append:\n{list_of_values}")
    print(f"Updated array:\n{arr_updated}")

In [15]:
# Using append_to_array function append list of values to array
sample_list = [40, 50, 60, 70, 80, 90]
sample_arr = np.array([10, 20, 30])
append_to_array(sample_arr, sample_list)

Orignal array:
[10 20 30]
List of values to append:
[40, 50, 60, 70, 80, 90]
Updated array:
[10 20 30 40 50 60 70 80 90]


10. **Write a Python program to find the real and imaginary parts of an array of complex numbers**

    Expected Output:\
    Original array\
    [ 1.00000000+0.j 0.70710678+0.70710678j]\
    Real part of the array:\
    [ 1. 0.70710678]\
    Imaginary part of the array:\
    [ 0. 0.70710678]

In [16]:
# function to extract real and imaginary part of numpy array of complex numbers
def real_imaginary(complex_arr: np.ndarray):
    """
        Description:
            Extracts real and imaginary part of the array
        
        Parameter:
            complex_arr: a numpy array of complex numbers
        
        Return:
            None
    """
    real_arr = complex_arr.real
    imaginary_arr = complex_arr.imag
    print(f"Original array:\n{complex_arr}")
    print(f"Real part:\n{real_arr}")
    print(f"Imaginary part:\n{imaginary_arr}")

In [17]:
# Using the above method extract real and imaginary parts of complex array
complex_arr = np.array([1+4j, 2+1j, 4+5j])
real_imaginary(complex_arr)

Original array:
[1.+4.j 2.+1.j 4.+5.j]
Real part:
[1. 2. 4.]
Imaginary part:
[4. 1. 5.]


11. **Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements**

    Expected Output:\
    Size of the array: 3\
    Length of one array element in bytes: 8\
    Total bytes consumed by the elements of the array: 24

In [18]:
# A function to display the size, size as bytes, element size as bytes of an array
def array_size_info(arr: np.ndarray):
    """
        Description:
            displays the size, size as bytes, element size as bytes of an array
        
        Parameter:
            arr: a numpy array
        
        Return:
            None
    """
    arr_size = arr.size
    element_size_as_bytes = arr.itemsize
    arr_size_as_bytes = arr_size * element_size_as_bytes
    print(f"Size of the array: {arr_size}")
    print(f"Length of one array element in bytes: {element_size_as_bytes}")
    print(f"Total bytes consumed by the elements of the array: {arr_size_as_bytes}")

In [19]:
# Using the above method get arrays size info
sample_arr = np.array([1.4, 1, 5])
array_size_info(sample_arr)

Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


12. **Write a Python program to find common values between two arrays**

    Expected Output:\
    Array1: [ 0 10 20 40 60]\
    Array2: [10, 30, 40]\
    Common values between two arrays: [10 40]

In [20]:
# Function that finds the intersecting values of 2 arrays
def common_values(arr1: np.ndarray, arr2: np.ndarray):
    """
        Description:
            finds the intersecting values of 2 arrays
        
        Parameter:
            arr1, arr2: 2 numpy arrays
        
        Return:
            None
    """
    common_val = np.intersect1d(arr1, arr2)
    print(f"Array 1: {arr1}")
    print(f"Array 2: {arr2}")
    print(f"Common values between the 2 arrays: {common_val}")

In [21]:
# Using the above method get common values of 2 arrays
sample_arr1 = np.array([0, 10, 20, 40, 60])
sample_arr2 = np.array([10, 30, 40])
common_values(sample_arr1, sample_arr2)

Array 1: [ 0 10 20 40 60]
Array 2: [10 30 40]
Common values between the 2 arrays: [10 40]


13. **Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2**

    Expected Output:\
    Array1: [ 0 10 20 40 60 80]\
    Array2: [10, 30, 40, 50, 70, 90]\
    Set difference between two arrays: [ 0 20 60 80]

In [22]:
# Function that finds the array difference of 2 arrays
def arr_diff(arr1: np.ndarray, arr2: np.ndarray):
    """
        Description:
            finds the array difference of 2 arrays
        
        Parameter:
            arr1, arr2: 2 numpy arrays
        
        Return:
            None
    """
    setdiff = np.setdiff1d(arr1, arr2)
    print(f"Array 1: {arr1}")
    print(f"Array 2: {arr2}")
    print(f"Set difference between 2 arrays: {setdiff}")

In [23]:
# Using the above method get array difference of 2 arrays
sample_arr1 = np.array([0, 10, 20, 40, 60, 80])
sample_arr2 = np.array([10, 30, 40, 50, 70, 90])
arr_diff(sample_arr1, sample_arr2)

Array 1: [ 0 10 20 40 60 80]
Array 2: [10 30 40 50 70 90]
Set difference between 2 arrays: [ 0 20 60 80]


14. **Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays**

    Array1: [ 0 10 20 40 60 80]\
    Array2: [10, 30, 40, 50, 70]\
    Unique values that are in only one (not both) of the input arrays:\
    [ 0 20 30 50 60 70 80]

In [24]:
# Function that finds the set exclusive-or of 2 arrays
def arr_diff(arr1: np.ndarray, arr2: np.ndarray):
    """
        Description:
            finds the set exclusive-or of 2 arrays
        
        Parameter:
            arr1, arr2: 2 numpy arrays
        
        Return:
            None
    """
    setdiff = np.setxor1d(arr1, arr2)
    print(f"Array 1: {arr1}")
    print(f"Array 2: {arr2}")
    print(f"Unique values that are in only one (not both) of the input arrays:\n{setdiff}")

In [25]:
# Using the above method get set exclusive-or of 2 arrays
sample_arr1 = np.array([0, 10, 20, 40, 60, 80])
sample_arr2 = np.array([10, 30, 40, 50, 70])
arr_diff(sample_arr1, sample_arr2)

Array 1: [ 0 10 20 40 60 80]
Array 2: [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


15. **Write a Python program compare two arrays using numpy**

    Array a: [1 2]\
    Array b: [4 5]\
    a > b\
    [False False]\
    a >= b\
    [False False]\
    a < b\
    [ True True]\
    a <= b\
    [ True True]

In [26]:
# function to compare 2 arrays
def compare_arr(arr_a: np.ndarray, arr_b: np.ndarray):
    """
        Description:
            Compares 2 arrays
        
        Parameter:
            arr1, arr2: 2 numpy arrays
        
        Return:
            None
    """
    print(f"Array a: {arr_a}")
    print(f"Array b: {arr_b}")
    print(f"a > b:\n{arr_a > arr_b}")
    print(f"a >= b:\n{arr_a >= arr_b}")
    print(f"a < b:\n{arr_a < arr_b}")
    print(f"a <= b:\n{arr_a <= arr_b}")

In [27]:
# Using above function to compare 2 arrays
sample_a = np.array([1, 2])
sample_b = np.array([4, 5])
compare_arr(sample_a, sample_b)

Array a: [1 2]
Array b: [4 5]
a > b:
[False False]
a >= b:
[False False]
a < b:
[ True  True]
a <= b:
[ True  True]


15. b)**Write a Python program to save a NumPy array to a text file**

In [28]:
# Create an array
sample_arr = np.arange(0,100, step=5)
arr2D = sample_arr.reshape((5,4)) 
print('Array:\n', arr2D)
 
# Saving the array in a text file
file = open("array_file.txt", "w")
content = str(arr2D)
file.write(content)
file.close()

Array:
 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]


16. **Write a Python program to create a contiguous flattened array**

    Original array:\
    [[10 20 30]\
    [20 40 50]]\
    New flattened array:\
    [10 20 30 20 40 50]

In [29]:
# Function to flatten any given numpy array

def flatten_arr(arr: np.ndarray):
    """
        Description:
            Flattens the array to 1D
        
        Parameter:
            arr: a numpy array
        
        Return:
            None
    """
    flattened_arr = arr.flatten()
    print(f"Original array:\n{arr}")
    print(f"Flattened array:\n{flattened_arr}")

In [30]:
# Using above function flatten a multi dimensional array
arr1D = np.arange(1,28)
multi_dim_arr = arr1D.reshape((3,3,3))
flatten_arr(multi_dim_arr)

Original array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


17. **Write a Python program to change the data type of an array**

    Expected Output:\
    [[ 2 4 6]\
    [ 6 8 10]]\
    Data type of the array x is: int32\
    New Type: float64\
    [[ 2. 4. 6.]\
    [ 6. 8. 10.]]

In [31]:
# create an int array
int32_arr = np.array([[2,4,6],[6,8,10]], dtype=np.int32)
float64_arr = int32_arr.astype('float64')
int16_arr = int32_arr.astype('int16')

print(f"Original array:\n{int32_arr}")
print(f"Data type of array: {int32_arr.dtype}")
print(f"New type 1: {float64_arr.dtype}")
print(f"Float64 array:\n{float64_arr}")
print(f"New type 2: {int16_arr.dtype}")
print(f"Int16 array:\n{int16_arr}")

Original array:
[[ 2  4  6]
 [ 6  8 10]]
Data type of array: int32
New type 1: float64
Float64 array:
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
New type 2: int16
Int16 array:
[[ 2  4  6]
 [ 6  8 10]]


18. **Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere**

    Expected Output:\
    [[ 1. 0. 0.]\
    [ 0. 1. 0.]\
    [ 0. 0. 1.]]

In [33]:
# Create 3x3 matrix of zeroes
matrix_3x3 = np.zeros((3,3))

#Set Diagonal's value as 1
np.fill_diagonal(matrix_3x3, 1)

print(f"Matrix:\n{matrix_3x3}")

Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. **Write a Python program to create an array which looks like below array**

    Expected Output:\
    [[ 0. 0. 0.]\
    [ 1. 0. 0.]\
    [ 1. 1. 0.]

In [42]:
# Set values above the lower triangle to 0 using the tril() method
lower_triangle_matrix = np.tril(np.ones((3,3)), k=-1)

print(f"Matrix:\n{lower_triangle_matrix}")

Matrix:
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]
